#!/usr/bin/env bash

PACKAGE="lied"
VERSION="$(git describe --tags --always --dirty)"
COMMIT_HASH="$(git rev-parse --short HEAD)"
BUILD_TIME=$(date '+%Y%m%d-%H%M%S')

LDFLAGS=(
  "-X '${PACKAGE}/version.Version=${VERSION}'"
  "-X '${PACKAGE}/version.CommitHash=${COMMIT_HASH}'"
  "-X '${PACKAGE}/version.BuildTime=${BUILD_TIME}'"
)

go build -ldflags="${LDFLAGS[*]}"
